//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchMaker.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entertainment
    {
        public Entertainment()
        {
            this.User_Entertainment = new HashSet<User_Entertainment>();
        }
    
        public int GenreId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User_Entertainment> User_Entertainment { get; set; }
    }
}
