//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchMaker.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Music
    {
        public Music()
        {
            this.User_Music = new HashSet<User_Music>();
        }
    
        public int GenreId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<User_Music> User_Music { get; set; }
    }
}
