//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchMaker.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.User_Books = new HashSet<User_Books>();
            this.User_Entertainment = new HashSet<User_Entertainment>();
            this.User_ExpArts = new HashSet<User_ExpArts>();
            this.User_Music = new HashSet<User_Music>();
            this.User_Sport = new HashSet<User_Sport>();
            this.UserMatches = new HashSet<UserMatch>();
            this.UserMatches1 = new HashSet<UserMatch>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> NacDate { get; set; }
        public string Gender { get; set; }
        public string GenderPref { get; set; }
        public string Email { get; set; }
        public Nullable<int> Faculty { get; set; }
        public Nullable<int> TravelW { get; set; }
        public Nullable<int> TechW { get; set; }
        public string ImageURL { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual ICollection<User_Books> User_Books { get; set; }
        public virtual ICollection<User_Entertainment> User_Entertainment { get; set; }
        public virtual ICollection<User_ExpArts> User_ExpArts { get; set; }
        public virtual ICollection<User_Music> User_Music { get; set; }
        public virtual ICollection<User_Sport> User_Sport { get; set; }
        public virtual ICollection<UserMatch> UserMatches { get; set; }
        public virtual ICollection<UserMatch> UserMatches1 { get; set; }
    }
}
