//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchMaker.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_ExpArts
    {
        public int MatchId { get; set; }
        public System.Guid UserId { get; set; }
        public int GenreId { get; set; }
    
        public virtual ExpArt ExpArt { get; set; }
        public virtual User User { get; set; }
    }
}
